---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 30%
      maxUnavailable: 30%
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend
      containers:
        - name: frontend
          image: ghcr.io/goodfood-cesi/frontend:v1.0.9
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 400m
            requests:
              cpu: 200m
          env:
            - name: PORT
              value: '80'
            - name: RECAPTCHA_SITE_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RECAPTCHA_SITE_KEY
            - name: PAYPAL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: PAYPAL_CLIENT_ID
            - name: AUTH_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AUTH_API_URL
            - name: RESTAURANTS_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RESTAURANTS_API_URL
            - name: ORDERS_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: ORDERS_API_URL
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: frontend
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 25
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
        - type: Percent
          value: 50
          periodSeconds: 15
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
