apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend
      containers:
        - name: front
          image: ghcr.io/goodfood-cesi/frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: AUTH_API_URL
              value: "https://api.ksu.li/auth"
            - name: RESTAURANTS_API_URL
              value: "https://api.ksu.li/restaurants"
            - name: ORDERS_API_URL
              value: "https://api.ksu.li/orders"
            - name: RECAPTCHA_SITE_KEY
              value: "6LdZUkgeAAAAAOCy6HDgIzbZh_4lX004v2Zdn_J2"
            - name: PAYPAL_CLIENT_ID
              value: "AWCN7QeLEn14137jaS4iX2h5Q0zXGHJn_my-7-xZ_3V2nM0mQv9sbjdPdogD7hTHGltR5FxhNn3ojKRA"
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
#  annotations:
#    service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: 540c6e62-93a7-4f40-995a-7d075f14884f
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: frontend
  type: LoadBalancer
