apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: frontend
      containers:
        - name: front
          image: ghcr.io/goodfood-cesi/frontend:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: '8080'
            - name: AUTH_API_URL
              value: 'https://api.ksu.li/auth'
            - name: RESTAURANTS_API_URL
              value: 'https://api.ksu.li/restaurants'
            - name: ORDERS_API_URL
              value: 'https://api.ksu.li/orders'
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  annotations:
    service.beta.kubernetes.io/scw-loadbalancer-certificate-ids: 746f9a1a-4518-4685-bcd2-1ff5af386f34
spec:
  ports:
    - port: 443
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: frontend
  type: LoadBalancer
